name: Node.js Package

on:
  push:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: npm install express mongoose bcryptjs jsonwebtoken
    - run: npm test
       
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16

  publish-npm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
